'use client';

import { useState } from 'react';
import { useAccount } from 'wagmi';
import { ConnectWallet } from '@/components/ConnectWallet';

export interface ProofData {
  consentId: string;
  nullifier: string;
  proof: {
    a: [string, string];
    b: [[string, string], [string, string]];
    c: [string, string];
  };
}

export default function LoginPage() {
  const { isConnected } = useAccount();
  const [proofJson, setProofJson] = useState('');
  const [error, setError] = useState('');
  const [parsed, setParsed] = useState<ProofData | null>(null);

  function handleParse() {
    setError('');
    try {
      const data = JSON.parse(proofJson);
      if (!data.consentId || !data.nullifier || !data.proof) {
        setError('Invalid proof format. Required: consentId, nullifier, proof');
        return;
      }
      setParsed(data as ProofData);
      // Store in sessionStorage for verify page
      sessionStorage.setItem('proofData', JSON.stringify(data));
    } catch {
      setError('Invalid JSON.');
    }
  }

  if (!isConnected) {
    return (
      <div className="max-w-lg mx-auto py-16 text-center">
        <h1 className="text-2xl font-bold mb-4">Service Provider Login</h1>
        <p className="text-gray-500 mb-4">
          Connect your wallet to begin the privacy-preserving verification flow.
        </p>
        <ConnectWallet />
      </div>
    );
  }

  return (
    <div className="max-w-lg mx-auto">
      <h1 className="text-2xl font-bold mb-2">Login With Privacy</h1>
      <p className="text-sm text-gray-500 mb-6">
        Paste the proof data generated by your User Vault. Your identity remains private.
      </p>

      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium mb-1">Proof Data (JSON)</label>
          <textarea
            value={proofJson}
            onChange={(e) => setProofJson(e.target.value)}
            placeholder='{"consentId":"0x...","nullifier":"0x...","proof":{"a":[...],"b":[[...],[...]],"c":[...]}}'
            className="w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-transparent text-xs font-mono h-40"
          />
        </div>

        <button
          onClick={handleParse}
          className="w-full px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium"
        >
          Parse Proof
        </button>

        {error && <p className="text-sm text-red-600 dark:text-red-400">{error}</p>}

        {parsed && (
          <div className="p-4 border border-green-200 dark:border-green-800 bg-green-50 dark:bg-green-900/20 rounded-lg">
            <p className="text-sm text-green-800 dark:text-green-200 font-medium mb-2">
              Proof parsed successfully
            </p>
            <div className="text-xs font-mono text-green-700 dark:text-green-300 space-y-1">
              <p>consentId: {parsed.consentId}</p>
              <p>nullifier: {parsed.nullifier}</p>
            </div>
            <a
              href="/verify"
              className="mt-3 inline-block text-sm text-green-900 dark:text-green-100 underline"
            >
              Proceed to Verification
            </a>
          </div>
        )}
      </div>
    </div>
  );
}
