'use client';

import { useState } from 'react';
import { useAccount } from 'wagmi';
import { ConnectWallet } from '@/components/ConnectWallet';

export interface ProofData {
  consentId: string;
  nullifier: string;
  proof: {
    a: [string, string];
    b: [[string, string], [string, string]];
    c: [string, string];
  };
}

export default function LoginPage() {
  const { isConnected } = useAccount();
  const [proofJson, setProofJson] = useState('');
  const [error, setError] = useState('');
  const [parsed, setParsed] = useState<ProofData | null>(null);

  function handleParse() {
    setError('');
    try {
      const data = JSON.parse(proofJson);
      if (!data.consentId || !data.nullifier || !data.proof) {
        setError('Invalid proof format. Required: consentId, nullifier, proof');
        return;
      }

      // Validate bytes32 format for consentId and nullifier
      const bytes32Regex = /^0x[0-9a-fA-F]{64}$/;
      if (!bytes32Regex.test(data.consentId)) {
        setError('consentId must be a bytes32 value (0x + 64 hex chars).');
        return;
      }
      if (!bytes32Regex.test(data.nullifier)) {
        setError('nullifier must be a bytes32 value (0x + 64 hex chars).');
        return;
      }

      // Validate proof structure: a=[2], b=[2][2], c=[2]
      const { a, b, c } = data.proof;
      if (
        !Array.isArray(a) ||
        a.length !== 2 ||
        !Array.isArray(b) ||
        b.length !== 2 ||
        !Array.isArray(b[0]) ||
        b[0].length !== 2 ||
        !Array.isArray(b[1]) ||
        b[1].length !== 2 ||
        !Array.isArray(c) ||
        c.length !== 2
      ) {
        setError('Invalid proof structure: a must be [2], b must be [2][2], c must be [2].');
        return;
      }

      setParsed(data as ProofData);
      sessionStorage.setItem('proofData', JSON.stringify(data));
    } catch {
      setError('Invalid JSON.');
    }
  }

  if (!isConnected) {
    return (
      <div className="wallet-gate">
        <p className="wallet-gate-eyebrow">Wallet Required</p>
        <h1 className="wallet-gate-heading">Connect your wallet to continue</h1>
        <p className="wallet-gate-desc">
          Connect your wallet to begin the privacy-preserving verification flow.
        </p>
        <ConnectWallet />
      </div>
    );
  }

  return (
    <>
      {/* Hero */}
      <section className="hero">
        <p className="eyebrow">Service Provider</p>
        <h1 className="hero-title">
          Verify
          <br />
          <span className="muted">access.</span>
        </h1>
        <div className="hero-body">
          <p className="hero-desc">
            Paste the Zero-Knowledge Proof generated by your User Vault. Your identity remains
            private — only consent validity is verified on-chain.
          </p>
        </div>
      </section>

      {/* Form */}
      <div className="content-section">
        <div className="form-group">
          <label className="rtf-label">Proof Data (JSON)</label>
          <textarea
            value={proofJson}
            onChange={(e) => setProofJson(e.target.value)}
            placeholder='{"consentId":"0x...","nullifier":"0x...","proof":{"a":[...],"b":[[...],[...]],"c":[...]}}'
            className="rtf-textarea"
          />
        </div>

        <button
          onClick={handleParse}
          className={`${
            proofJson.trim() && !error ? 'btn-primary' : 'btn-ghost'
          } btn-primary--full`}
        >
          Submit Proof
        </button>

        {/* Error */}
        {error && (
          <div className="state-error">
            <span className="state-error-dot"></span>
            <span className="state-error-text">{error}</span>
          </div>
        )}

        {/* Parsed Success */}
        {parsed && (
          <div className="state-success">
            <div className="state-success-row">
              <span className="state-success-dot"></span>
              <span className="state-success-text">Proof parsed successfully</span>
            </div>
            <p className="state-success-detail">consentId: {parsed.consentId}</p>
            <p className="state-success-detail">nullifier: {parsed.nullifier}</p>
            <a
              href="/verify"
              className="btn-primary"
              style={{ display: 'inline-block', marginTop: 'var(--gap-16)' }}
            >
              Proceed to Verification
            </a>
          </div>
        )}
      </div>

      {/* Bottom Bar */}
      <div className="bottom-spacer"></div>
      <div className="bottom-bar">
        <div className="bb-left">
          <span className="bb-item">
            <span className="bb-dot"></span>connected
          </span>
        </div>
        <div className="bb-right">
          <span className="bb-item">polygon amoy</span>
          <div className="bb-sep"></div>
          <span className="bb-item">v1.0.0</span>
        </div>
      </div>
    </>
  );
}
